import { Category, Allergen, Extra, Product } from '@/types/menu';
import { Restaurant } from '@/types/restaurant';

export const INITIAL_CATEGORIES: Category[] = [
  { id: '1', name: 'Burger del Mes', slug: 'burger-del-mes', displayOrder: 1, icon: 'Flame' },
  { id: '2', name: 'Entrantes', slug: 'entrantes', displayOrder: 2, icon: 'Utensils' },
  { id: '3', name: 'Clásicas', slug: 'clasicas', displayOrder: 3, icon: 'Beef' },
  { id: '4', name: 'Especiales', slug: 'especiales', displayOrder: 4, icon: 'Sparkles' },
  { id: '5', name: 'Menú Infantil', slug: 'infantil', displayOrder: 5, icon: 'Baby' },
  { id: '6', name: 'Sandwiches & Hotdogs', slug: 'sandwiches-hotdogs', displayOrder: 6, icon: 'Salad' },
  { id: '7', name: 'Postres', slug: 'postres', displayOrder: 7, icon: 'Cake' },
  { id: '8', name: 'Shakes', slug: 'shakes', displayOrder: 8, icon: 'CupSoda' },
  { id: '9', name: 'Bebidas', slug: 'bebidas', displayOrder: 9, icon: 'Beer' },
];

export const INITIAL_ALLERGENS: Allergen[] = [
  { id: 'gluten', name: 'Gluten', icon: '🌾' },
  { id: 'lacteos', name: 'Lácteos', icon: '🥛' },
  { id: 'huevos', name: 'Huevos', icon: '🥚' },
  { id: 'frutos_secos', name: 'Frutos Secos', icon: '🥜' },
  { id: 'mostaza', name: 'Mostaza', icon: '🍯' },
  { id: 'soja', name: 'Soja', icon: '🫘' },
  { id: 'pescado', name: 'Pescado', icon: '🐟' },
];

export const INITIAL_EXTRAS: Extra[] = [
  { id: 'cheddar', name: 'Extra queso cheddar', price: 1.50 },
  { id: 'bacon', name: 'Bacon crujiente', price: 1.50 },
  { id: 'huevo', name: 'Huevo frito', price: 1.20 },
  { id: 'carne', name: 'Doble carne artesanal', price: 3.50 },
  { id: 'salsa', name: 'Salsa Flanagans extra', price: 0.80 },
  { id: 'singluten', name: 'Pan sin gluten', price: 1.00 },
  { id: 'patatas', name: 'Ración extra de patatas', price: 2.50 },
  { id: 'bebida', name: 'Bebida extra', price: 2.00 },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- BURGER DEL MES ---
  {
    id: 'b-mes',
    restaurantId: 'flanagans',
    name: 'La Smashzilla 5.0',
    slug: 'la-smashzilla',
    category: 'burger-del-mes',
    price: 18.00,
    description: '5 carnes smash, 4 lonchas de queso cheddar ahumado, salsa cheddar y bits de bacon.',
    ingredients: ['5 carnes smash', '4 lonchas de queso cheddar ahumado', 'Salsa cheddar', 'Bits de bacon'],
    allergens: ['gluten', 'lacteos', 'soja'],
    tags: ['Burger del Mes', 'Top Ventas', 'Recomendada'],
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    posterImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    videoUrl: '/videomenu/hamburguesas/la_smashzilla.webm',
    isAvailable: true,
    isFeatured: true,
    isCampaign: true,
    campaignLabel: 'Burger del Mes',
    displayOrder: 1,
    isProfitable: true,
    extras: ['singluten'],
  },

  // --- ENTRANTES ---
  {
    id: 'ent-ensalada-cesar',
    restaurantId: 'flanagans',
    name: 'Ensalada César',
    slug: 'ensalada-cesar',
    category: 'entrantes',
    price: 10.90,
    description: 'Pollo crujiente, picatostes, queso parmesano y salsa César.',
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 2,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos', 'mostaza'],
  },
  {
    id: 'ent-ensalada-ny',
    restaurantId: 'flanagans',
    name: 'Ensalada New York',
    slug: 'ensalada-new-york',
    category: 'entrantes',
    price: 11.90,
    description: 'Pastrami, tomates cherry, frutos secos y salsa de mostaza y miel.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 3,
    isProfitable: true,
    allergens: ['mostaza', 'frutos_secos'],
  },
  {
    id: 'ent-ensalada-salmon',
    restaurantId: 'flanagans',
    name: 'Ensalada de salmón ahumado',
    slug: 'ensalada-salmon',
    category: 'entrantes',
    price: 12.50,
    description: 'Salmón ahumado, tomates cherry, cebolla frita y salsa tártara.',
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 4,
    isProfitable: true,
    allergens: ['pescado', 'gluten', 'huevos'],
  },
  {
    id: 'ent-ensalada-cabra',
    restaurantId: 'flanagans',
    name: 'Ensalada de rulo de cabra',
    slug: 'ensalada-rulo-cabra',
    category: 'entrantes',
    price: 11.50,
    description: 'Queso de cabra, tomates cherry, frutos secos y salsa de frutos rojos.',
    imageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 5,
    isProfitable: true,
    allergens: ['lacteos', 'frutos_secos'],
  },
  {
    id: 'ent-patatas-carne',
    restaurantId: 'flanagans',
    name: 'Patatas gratinadas con carne',
    slug: 'patatas-gratinadas-carne',
    category: 'entrantes',
    price: 10.00,
    description: 'Patatas gratinadas con mix de quesos y carne pulled pork.',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 6,
    isProfitable: true,
    allergens: ['lacteos'],
  },
  {
    id: 'ent-alitas',
    restaurantId: 'flanagans',
    name: 'Alitas Flanagan\'s Style',
    slug: 'alitas-flanagans',
    category: 'entrantes',
    price: 10.50,
    description: 'Alitas con salsa BBQ casera y toque de chile agridulce.',
    imageUrl: 'https://images.unsplash.com/photo-1564834724105-918b73d1b9e0?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 7,
    isProfitable: true,
  },
  {
    id: 'ent-nachos',
    restaurantId: 'flanagans',
    name: 'Nachos Flanagan\'s Version',
    slug: 'nachos-flanagans',
    category: 'entrantes',
    price: 11.00,
    description: 'Nachos con queso fundido, guacamole, crema agria y carne con chile.',
    imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 8,
    isProfitable: true,
    allergens: ['lacteos'],
  },
  {
    id: 'ent-tiras-pollo',
    restaurantId: 'flanagans',
    name: 'Tiras de pollo marinadas',
    slug: 'tiras-pollo',
    category: 'entrantes',
    price: 10.50,
    description: 'Pollo con empanado crujiente, acompañado de salsa de mostaza y miel.',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 9,
    isProfitable: true,
    allergens: ['gluten', 'mostaza'],
  },
  {
    id: 'ent-lingotes-queso',
    restaurantId: 'flanagans',
    name: 'Lingotes de queso',
    slug: 'lingotes-queso',
    category: 'entrantes',
    price: 10.50,
    description: 'Queso frito con mermelada de tomate para dipear.',
    imageUrl: 'https://images.unsplash.com/photo-1627976860475-74895690b200?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 10,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
  },
  {
    id: 'ent-aros-cebolla',
    restaurantId: 'flanagans',
    name: 'Aros de cebolla',
    slug: 'aros-cebolla',
    category: 'entrantes',
    price: 10.00,
    description: 'Aros de cebolla hechos en casa.',
    imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 11,
    isProfitable: true,
    allergens: ['gluten'],
  },
  {
    id: 'ent-tacos',
    restaurantId: 'flanagans',
    name: 'Tacos de cochinita pibil',
    slug: 'tacos-cochinita',
    category: 'entrantes',
    price: 11.90,
    description: 'Cochinita pibil con mahonesa de chipotle, guacamole, mezcla de queso y cebolla encurtida.',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 12,
    isProfitable: true,
    allergens: ['lacteos', 'huevos'],
  },
  {
    id: 'ent-holy-guaca',
    restaurantId: 'flanagans',
    name: 'Holy Guaca',
    slug: 'holy-guaca',
    category: 'entrantes',
    price: 14.00, // Tomaremos el precio de ración completa como base
    description: 'Guacamole servido en mesa con pico de gallo y totopos de maíz caseros. Opción de agregar picante. (Ración 14,00 € / Media ración 12,00 €)',
    imageUrl: 'https://images.unsplash.com/photo-1549488344-c6af94254179?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 13,
    isProfitable: true,
  },

  // --- CLÁSICAS ---
  {
    id: 'c-clasica',
    restaurantId: 'flanagans',
    name: 'La Clásica',
    slug: 'la-clasica',
    category: 'clasicas',
    price: 11.90,
    description: 'Carne 180 g, lechuga, tomate, cebolla, queso cheddar, queso Edam, bacon y mahonesa.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 14,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'c-mostoles',
    restaurantId: 'flanagans',
    name: 'Móstoles Style',
    slug: 'mostoles-style',
    category: 'clasicas',
    price: 13.40,
    description: 'Carne 180 g, lechuga, tomate, queso de cabra, cebolla caramelizada, bacon y mahonesa BBQ.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 15,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'c-pulled-pork',
    restaurantId: 'flanagans',
    name: 'Pulled Pork',
    slug: 'pulled-pork',
    category: 'clasicas',
    price: 12.90,
    description: 'Carne 100 g, tomate, queso cheddar, queso Edam, aro de cebolla, pulled pork, mahonesa BBQ y salsa BBQ.',
    imageUrl: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 16,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'c-chicken',
    restaurantId: 'flanagans',
    name: 'Chicken Burguer',
    slug: 'chicken-burguer',
    category: 'clasicas',
    price: 11.90,
    description: 'Hamburguesa de contramuslo, lechuga, tomate, queso Edam, bacon, cebolla morada y mayo chipotle.',
    imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 17,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'c-iberica',
    restaurantId: 'flanagans',
    name: 'La Ibérica',
    slug: 'la-iberica',
    category: 'clasicas',
    price: 11.90,
    description: 'Carne de cerdo ibérico, lechuga, cebolla, tomate, queso cheddar, queso Edam, sobrasada y alioli dulce.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 18,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },

  // --- MENÚ INFANTIL ---
  {
    id: 'mi-1',
    restaurantId: 'flanagans',
    name: 'Menú infantil 1',
    slug: 'menu-infantil-1',
    category: 'infantil',
    price: 10.90,
    description: 'Cheeseburger o chicken burger con queso, patatas fritas, bebida y helado.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 19,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
  },
  {
    id: 'mi-2',
    restaurantId: 'flanagans',
    name: 'Menú infantil 2',
    slug: 'menu-infantil-2',
    category: 'infantil',
    price: 10.90,
    description: 'Mac and cheese, patatas fritas, bebida y helado.',
    imageUrl: 'https://images.unsplash.com/photo-1620025737522-3783a30c0003?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 20,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
  },

  // --- ESPECIALES ---
  {
    id: 'e-flanagan-smash',
    restaurantId: 'flanagans',
    name: 'Flanagan Smash',
    slug: 'flanagan-smash',
    category: 'especiales',
    price: 14.90,
    description: '4 carnes de 100 g cada una, doble queso y salsa cheddar.',
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 21,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
    extras: ['singluten'],
  },
  {
    id: 'e-red-21',
    restaurantId: 'flanagans',
    name: 'Red 21',
    slug: 'red-21',
    category: 'especiales',
    price: 15.00,
    description: '200 g de carne Angus, costilla desmenuzada cocida a baja temperatura durante 60 horas, queso suizo, cebolla caramelizada y salsa trufada.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 22,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
    extras: ['singluten'],
  },
  {
    id: 'e-trufada',
    restaurantId: 'flanagans',
    name: 'La Trufada',
    slug: 'la-trufada',
    category: 'especiales',
    price: 15.00,
    description: 'Carne 180 g, cebolla caramelizada, queso provolone, huevo y salsa de trufa casera.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 23,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'e-4-quesos',
    restaurantId: 'flanagans',
    name: '4 Quesos Sweet Bacon',
    slug: '4-quesos-sweet-bacon',
    category: 'especiales',
    price: 14.90,
    description: 'Carne 180 g, mix de mozzarella, gorgonzola, emmental y cheddar, lechuga, cebolla morada y mahonesa.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 24,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'e-emmy',
    restaurantId: 'flanagans',
    name: 'La Emmy',
    slug: 'la-emmy',
    category: 'especiales',
    price: 15.00,
    description: 'Doble carne smash, pan de cristal, queso cheddar ahumado, cebolla encurtida, bacon crujiente y salsa Emmy con toque picante.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 25,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
    extras: ['singluten'],
  },
  {
    id: 'e-vegan',
    restaurantId: 'flanagans',
    name: 'Vegan Burguer',
    slug: 'vegan-burguer',
    category: 'especiales',
    price: 14.50,
    description: 'Beyond Burger, lechuga, tomate, cebolla, calabacín y salsa romesco.',
    imageUrl: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 26,
    isProfitable: true,
    allergens: ['gluten'],
    extras: ['singluten'],
  },
  {
    id: 'e-smoky',
    restaurantId: 'flanagans',
    name: 'Smoky Queen',
    slug: 'smoky-queen',
    category: 'especiales',
    price: 15.00,
    description: 'Carne 180 g, brotes tiernos de canónigos, queso blanco ahumado, mayonesa ahumada y cebolla frita.',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 27,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
    extras: ['singluten'],
  },
  {
    id: 'e-smash-ny',
    restaurantId: 'flanagans',
    name: 'Smash New York Style',
    slug: 'smash-new-york-style',
    category: 'especiales',
    price: 13.90,
    description: 'Doble carne de 100 g, queso cheddar, bacon, pepinillos y salsa Secret Soul.',
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 28,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
    extras: ['singluten'],
  },
  {
    id: 'e-maple',
    restaurantId: 'flanagans',
    name: 'The Maple',
    slug: 'the-maple',
    category: 'especiales',
    price: 15.00,
    description: 'Dos carnes de 90 g, queso cheddar ahumado, bacon y cebolla caramelizada con sirope Maple.',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 29,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
    extras: ['singluten'],
  },

  // --- SANDWICHES & HOTDOGS ---
  {
    id: 'sh-chicken-sand',
    restaurantId: 'flanagans',
    name: 'Chicken Sandwich',
    slug: 'chicken-sandwich',
    category: 'sandwiches-hotdogs',
    price: 10.90,
    description: 'Pollo crujiente, lechuga, tomate, queso cheddar, queso Edam y salsa de yogur.',
    imageUrl: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 30,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
  },
  {
    id: 'sh-street-meat',
    restaurantId: 'flanagans',
    name: 'Street Meat',
    slug: 'street-meat',
    category: 'sandwiches-hotdogs',
    price: 10.50,
    description: 'Salchicha, bacon, pulled pork, salsa cheddar y cebolla frita.',
    imageUrl: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 31,
    isProfitable: true,
    allergens: ['gluten', 'lacteos'],
  },
  {
    id: 'sh-pastrami',
    restaurantId: 'flanagans',
    name: 'Pastrami',
    slug: 'pastrami',
    category: 'sandwiches-hotdogs',
    price: 12.90,
    description: 'Pastrami, lechuga, tomate, pepinillo y mahonesa de mostaza antigua.',
    imageUrl: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 32,
    isProfitable: true,
    allergens: ['gluten', 'huevos', 'mostaza'],
  },
  {
    id: 'sh-salmon',
    restaurantId: 'flanagans',
    name: 'Salmón Ahumado',
    slug: 'salmon-ahumado',
    category: 'sandwiches-hotdogs',
    price: 11.90,
    description: 'Salmón ahumado, lechuga, tomate, pepinillo y crema de queso.',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 33,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'pescado'],
  },
  {
    id: 'sh-clasico',
    restaurantId: 'flanagans',
    name: 'Clásico',
    slug: 'hotdog-clasico',
    category: 'sandwiches-hotdogs',
    price: 8.90,
    description: 'Salchicha, pepinillo, cebolla frita y mahonesa.',
    imageUrl: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 34,
    isProfitable: true,
    allergens: ['gluten', 'huevos'],
  },

  // --- POSTRES ---
  {
    id: 'p-coco-nocciola',
    restaurantId: 'flanagans',
    name: 'Coco Nocciola',
    slug: 'coco-nocciola',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de chocolate y coco.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 35,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
  },
  {
    id: 'p-tarta-pistacho',
    restaurantId: 'flanagans',
    name: 'Tarta de pistacho',
    slug: 'tarta-pistacho',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de queso y pistacho.',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 36,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos', 'frutos_secos'],
  },
  {
    id: 'p-toblerone',
    restaurantId: 'flanagans',
    name: 'Tarta de Toblerone',
    slug: 'tarta-toblerone',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de Toblerone, pensada como postre final.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 37,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos', 'frutos_secos'],
  },
  {
    id: 'p-cheesecake',
    restaurantId: 'flanagans',
    name: 'Cheesecake',
    slug: 'cheesecake',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de queso especial de la casa.',
    imageUrl: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 38,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
  },
  {
    id: 'p-brownie',
    restaurantId: 'flanagans',
    name: 'Brownie Homemade',
    slug: 'brownie-homemade',
    category: 'postres',
    price: 6.50,
    description: 'Brownie con helado de vainilla.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 39,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos', 'frutos_secos'],
  },
  {
    id: 'p-quesococo',
    restaurantId: 'flanagans',
    name: 'Tarta Quesococo',
    slug: 'tarta-quesococo',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de queso y coco con fina capa de chocolate.',
    imageUrl: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 40,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
  },
  {
    id: 'p-trilogia',
    restaurantId: 'flanagans',
    name: 'Trilogía de chocolate',
    slug: 'trilogia-chocolate',
    category: 'postres',
    price: 6.50,
    description: 'Tarta de triple chocolate.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 41,
    isProfitable: true,
    allergens: ['gluten', 'lacteos', 'huevos'],
  },

  // --- SHAKES ---
  {
    id: 'sh-chocolate',
    restaurantId: 'flanagans',
    name: 'Chocolate Shake',
    slug: 'chocolate-shake',
    category: 'shakes',
    price: 5.00,
    description: 'Shake de chocolate para acompañar la burger o tomar después.',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 42,
    isProfitable: true,
    allergens: ['lacteos'],
  },
  {
    id: 'sh-vainilla',
    restaurantId: 'flanagans',
    name: 'Vainilla Shake',
    slug: 'vainilla-shake',
    category: 'shakes',
    price: 5.00,
    description: 'Shake de vainilla.',
    imageUrl: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 43,
    isProfitable: true,
    allergens: ['lacteos'],
  },
  {
    id: 'sh-oreo',
    restaurantId: 'flanagans',
    name: 'Oreo Shake',
    slug: 'oreo-shake',
    category: 'shakes',
    price: 5.00,
    description: 'Shake de Oreo para acompañar la burger o tomar después.',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 44,
    isProfitable: true,
    allergens: ['lacteos', 'gluten'],
  },

  // --- BEBIDAS (Refrescos, Vinos, Copas) ---
  {
    id: 'beb-sprite',
    restaurantId: 'flanagans',
    name: 'Sprite',
    slug: 'sprite',
    category: 'bebidas',
    price: 3.50,
    description: 'Refresco Sprite.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 45,
    isProfitable: true,
  },
  {
    id: 'beb-cocacola',
    restaurantId: 'flanagans',
    name: 'Coca Cola',
    slug: 'coca-cola',
    category: 'bebidas',
    price: 3.50,
    description: 'Refresco Coca Cola clásico.',
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?q=80&w=800',
    isAvailable: true,
    isFeatured: true,
    isCampaign: false,
    displayOrder: 46,
    isProfitable: true,
  },
  {
    id: 'beb-cocacola-zero',
    restaurantId: 'flanagans',
    name: 'Coca Cola Zero',
    slug: 'coca-cola-zero',
    category: 'bebidas',
    price: 3.50,
    description: 'Refresco Coca Cola Zero.',
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 47,
    isProfitable: true,
  },
  {
    id: 'beb-fanta-limon',
    restaurantId: 'flanagans',
    name: 'Fanta Limón',
    slug: 'fanta-limon',
    category: 'bebidas',
    price: 3.50,
    description: 'Refresco Fanta Limón.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 48,
    isProfitable: true,
  },
  {
    id: 'beb-fanta-naranja',
    restaurantId: 'flanagans',
    name: 'Fanta Naranja',
    slug: 'fanta-naranja',
    category: 'bebidas',
    price: 3.50,
    description: 'Refresco Fanta Naranja.',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 49,
    isProfitable: true,
  },
  {
    id: 'beb-agua',
    restaurantId: 'flanagans',
    name: 'Agua Solán de Cabras',
    slug: 'agua-solan',
    category: 'bebidas',
    price: 2.20,
    description: 'Botella de agua mineral.',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 50,
    isProfitable: true,
  },
  {
    id: 'beb-copa-ron',
    restaurantId: 'flanagans',
    name: 'Copa de Ron',
    slug: 'copa-ron',
    category: 'bebidas',
    price: 7.00,
    description: 'Barceló o Legendario. (Suplemento Red Bull +1,00 €)',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 51,
    isProfitable: true,
  },
  {
    id: 'beb-copa-ginebra',
    restaurantId: 'flanagans',
    name: 'Copa de Ginebra',
    slug: 'copa-ginebra',
    category: 'bebidas',
    price: 7.00,
    description: 'Tanqueray, Puerto de Indias o Beefeater. (Suplemento Red Bull +1,00 €)',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800',
    isAvailable: true,
    isFeatured: false,
    isCampaign: false,
    displayOrder: 52,
    isProfitable: true,
  },
];

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'flanagans',
  name: 'Flanagans Burguer',
  logoUrl: '/logo.webp',
  brandColors: {
    primary: '#FACC15',
    secondary: '#000000',
    accent: '#EF4444',
  },
  phone: '919401241',
  whatsappNumber: '34919401241',
  instagramUrl: 'https://instagram.com/flanagansburguer',
  address: 'Calle Casiopea, 12, 28938 Móstoles, Madrid',
  openingHours: [
    { day: 'Lunes', hours: 'Cerrado' },
    { day: 'Martes', hours: '20:00 a 23:30' },
    { day: 'Miércoles', hours: '20:00 a 23:30' },
    { day: 'Jueves', hours: '13:00 a 16:30 y 20:00 a 23:30' },
    { day: 'Viernes', hours: '13:00 a 16:30 y 20:00 a 00:00' },
    { day: 'Sábado', hours: '13:00 a 16:30 y 20:00 a 00:00' },
    { day: 'Domingo', hours: '13:00 a 16:30 y 20:00 a 23:30' },
  ],
  welcomeMessage: '¡Bienvenido a Flanagans Burguer! Disfruta el sabor de una burguer de verdad. Carne de primera calidad.',
};
