import type { Promotion } from '@/lib/promotions-store';

export const DEFAULT_PROMOTIONS: Promotion[] = [
  {
    id: 'promo-efectivo',
    name: '15% Descuento Efectivo',
    label: '15% dto.',
    description: 'Disfruta de un 15% de descuento directo en toda tu cuenta al consumir en nuestro local y realizar tu pago en efectivo.',
    discountType: 'percent',
    discountValue: 15,
    isActive: true,
    productIds: [],
    color: 'primary',
    showBanner: false,
    showOnHome: true,
  },
  {
    id: 'promo-duo',
    name: 'Pack FlanaDuo para 2',
    label: 'Pack Duo',
    description: '2 Burgers clasicas o especiales + 1 entrante a elegir + 2 bebidas frias a un precio espectacular.',
    discountType: 'none',
    discountValue: 0,
    isActive: true,
    productIds: [],
    color: 'orange',
    showBanner: false,
    showOnHome: true,
  },
  {
    id: 'promo-takeaway',
    name: 'Take Away Dom a Jue',
    label: 'Take Away',
    description: 'Tus pedidos para recoger de domingo a jueves tienen premio: llevate patatas fritas gratis con cada burger.',
    discountType: 'none',
    discountValue: 0,
    isActive: true,
    productIds: [],
    color: 'red',
    showBanner: false,
    showOnHome: true,
  },
  {
    id: 'promo-semana',
    name: 'Promo de la Semana',
    label: 'Promo de la semana',
    description: 'Muestra esto en barra y recibe unas patatas gratis.',
    discountType: 'none',
    discountValue: 0,
    isActive: true,
    productIds: [],
    color: 'red',
    showBanner: true,
    showOnHome: false,
  },
];
